<?php

declare(strict_types=1);

namespace NtMcp\Admin;

use Illuminate\Database\Capsule\Manager as Capsule;
use NtMcp\Security\CsrfProtection;
use NtMcp\Whmcs\SystemUrl;

/**
 * Admin dashboard controller — Auth management UI.
 */
final class AdminController
{
    public function handle(array $vars): void
    {
        // Ensure session is started (needed for flash messages before CSRF token call)
        if (session_status() !== PHP_SESSION_ACTIVE) {
            @session_start();
        }

        $e = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $mcpUrl = SystemUrl::mcpUrl();

        // Auto-detect logged-in admin
        $currentAdminId = (int) ($_SESSION['adminid'] ?? 0);
        $currentAdminName = 'admin';
        if ($currentAdminId > 0) {
            try {
                $currentAdminName = Capsule::table('tbladmins')
                    ->where('id', $currentAdminId)
                    ->value('username') ?? 'admin';
            } catch (\Throwable $ex) {
                error_log('NT MCP Admin: Failed to look up admin username for ID ' . $currentAdminId . ': ' . $ex->getMessage());
            }
        }

        // Static token metadata
        $tokenAdmin   = trim(\WHMCS\Config\Setting::getValue('nt_mcp_bearer_token_admin') ?? '');
        $tokenCreated = trim(\WHMCS\Config\Setting::getValue('nt_mcp_bearer_token_created') ?? '');
        $tokenHash    = trim(\WHMCS\Config\Setting::getValue('nt_mcp_bearer_token') ?? '');

        // Handle POST actions — PRG via session flash + JS redirect
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $flashMessage   = '';
            $flashClass     = 'info';
            $flashPlaintext = '';

            $csrfOk = CsrfProtection::verify($_POST['_csrf_token'] ?? '');

            if (!$csrfOk) {
                $flashMessage = 'Erro: token CSRF invalido. Recarregue a pagina e tente novamente.';
                $flashClass   = 'danger';
            } elseif (isset($_POST['regenerate_token'])) {
                $newToken       = bin2hex(random_bytes(32));
                $hash           = hash('sha256', $newToken);
                \WHMCS\Config\Setting::setValue('nt_mcp_bearer_token', $hash);
                \WHMCS\Config\Setting::setValue('nt_mcp_bearer_token_admin', $currentAdminName);
                \WHMCS\Config\Setting::setValue('nt_mcp_bearer_token_created', date('Y-m-d H:i:s'));
                \WHMCS\Config\Setting::setValue('nt_mcp_admin_user', $currentAdminName);
                $flashPlaintext = $newToken;
                $flashMessage   = 'Token regenerado com sucesso. Copie-o agora; ele nao sera exibido novamente.';
                $flashClass     = 'success';
                logActivity("NT MCP: Bearer token regenerated by admin ID {$currentAdminId} ({$currentAdminName})");
            } elseif (isset($_POST['revoke_oauth_token'])) {
                $tokenId = (int) ($_POST['token_id'] ?? 0);
                if ($tokenId > 0) {
                    try {
                        Capsule::table('mod_nt_mcp_oauth_tokens')->where('id', $tokenId)->delete();
                        $flashMessage = 'Token OAuth revogado com sucesso.';
                        $flashClass   = 'success';
                        logActivity("NT MCP: OAuth token ID {$tokenId} revoked by admin ID {$currentAdminId} ({$currentAdminName})");
                    } catch (\Throwable $ex) {
                        error_log('NT MCP: Failed to revoke OAuth token: ' . $ex->getMessage());
                        $flashMessage = 'Erro ao revogar token. Verifique o log de erros.';
                        $flashClass   = 'danger';
                    }
                }
            } elseif (isset($_POST['revoke_all_oauth_tokens'])) {
                try {
                    $deleted = Capsule::table('mod_nt_mcp_oauth_tokens')->delete();
                    $flashMessage = $deleted . ' token(s) OAuth revogado(s).';
                    $flashClass   = 'success';
                    logActivity("NT MCP: All OAuth tokens revoked ({$deleted} total) by admin ID {$currentAdminId} ({$currentAdminName})");
                } catch (\Throwable $ex) {
                    error_log('NT MCP: Failed to revoke all OAuth tokens: ' . $ex->getMessage());
                    $flashMessage = 'Erro ao revogar tokens. Verifique o log de erros.';
                    $flashClass   = 'danger';
                }
            } elseif (isset($_POST['remove_oauth_client'])) {
                $clientIdToRemove = trim($_POST['client_id_remove'] ?? '');
                if ($clientIdToRemove !== '') {
                    try {
                        Capsule::connection()->transaction(function () use ($clientIdToRemove) {
                            Capsule::table('mod_nt_mcp_oauth_tokens')
                                ->where('client_id', $clientIdToRemove)->delete();
                            Capsule::table('mod_nt_mcp_oauth_codes')
                                ->where('client_id', $clientIdToRemove)->delete();
                            Capsule::table('mod_nt_mcp_oauth_clients')
                                ->where('client_id', $clientIdToRemove)->delete();
                        });
                        $flashMessage = 'Client OAuth removido junto com seus tokens.';
                        $flashClass   = 'success';
                        logActivity("NT MCP: OAuth client '{$clientIdToRemove}' removed by admin ID {$currentAdminId} ({$currentAdminName})");
                    } catch (\Throwable $ex) {
                        error_log('NT MCP: Failed to remove OAuth client: ' . $ex->getMessage());
                        $flashMessage = 'Erro ao remover client. Verifique o log de erros.';
                        $flashClass   = 'danger';
                    }
                }
            }

            // Store flash in session and redirect via JS (headers already sent in WHMCS _output)
            $_SESSION['nt_mcp_flash'] = [
                'message'   => $flashMessage,
                'class'     => $flashClass,
                'plaintext' => $flashPlaintext,
            ];
            $redirectUrl = self::addonUrl();
            echo '<script>window.location.replace(' . json_encode($redirectUrl) . ');</script>';
            return;
        }

        // GET: read flash from session
        $flashPlaintext = '';
        $flashMessage   = '';
        $flashClass     = 'info';
        if (isset($_SESSION['nt_mcp_flash'])) {
            $flash          = $_SESSION['nt_mcp_flash'];
            $flashMessage   = $flash['message'] ?? '';
            $flashClass     = $flash['class'] ?? 'info';
            $flashPlaintext = $flash['plaintext'] ?? '';
            unset($_SESSION['nt_mcp_flash']);
        }

        $csrf = CsrfProtection::token();

        // Load OAuth data
        $oauthTokens  = [];
        $oauthClients = [];
        $hasAdminUserCol  = false;
        $hasLastUsedAtCol = false;
        try {
            if (Capsule::schema()->hasTable('mod_nt_mcp_oauth_tokens')) {
                $hasAdminUserCol  = Capsule::schema()->hasColumn('mod_nt_mcp_oauth_tokens', 'admin_user');
                $hasLastUsedAtCol = Capsule::schema()->hasColumn('mod_nt_mcp_oauth_tokens', 'last_used_at');

                $query = Capsule::table('mod_nt_mcp_oauth_tokens')
                    ->leftJoin('mod_nt_mcp_oauth_clients', 'mod_nt_mcp_oauth_tokens.client_id', '=', 'mod_nt_mcp_oauth_clients.client_id')
                    ->select(
                        'mod_nt_mcp_oauth_tokens.id',
                        'mod_nt_mcp_oauth_tokens.client_id',
                        'mod_nt_mcp_oauth_tokens.expires_at',
                        'mod_nt_mcp_oauth_tokens.created_at',
                        'mod_nt_mcp_oauth_clients.client_name'
                    );
                if ($hasAdminUserCol) {
                    $query->addSelect('mod_nt_mcp_oauth_tokens.admin_user');
                }
                if ($hasLastUsedAtCol) {
                    $query->addSelect('mod_nt_mcp_oauth_tokens.last_used_at');
                }
                $oauthTokens = $query
                    ->orderBy('mod_nt_mcp_oauth_tokens.created_at', 'desc')
                    ->get()
                    ->all();
            }
            if (Capsule::schema()->hasTable('mod_nt_mcp_oauth_clients')) {
                $oauthClients = Capsule::table('mod_nt_mcp_oauth_clients')
                    ->orderBy('created_at', 'desc')
                    ->get()
                    ->all();
            }
        } catch (\Throwable $ex) {
            error_log('NT MCP Admin: Failed to load OAuth data: ' . $ex->getMessage());
            if ($flashMessage === '') {
                $flashMessage = 'Aviso: Nao foi possivel carregar dados OAuth. Verifique a conexao com o banco.';
                $flashClass   = 'warning';
            }
        }

        // Render template
        require dirname(__DIR__, 2) . '/templates/admin/dashboard.php';
    }

    private static function addonUrl(): string
    {
        return SystemUrl::resolve() . '/admin/addonmodules.php?module=nt_mcp';
    }
}
