<?php

declare(strict_types=1);

namespace NtMcp\Whmcs;

/** Eventos fechados do WHMCS Activity Log. Nenhum case contém dado externo. */
enum ActivityEvent: string
{
    case CONFIG_INVALID = 'MCP CONFIG INVALID';
    case API_BLOCKED_UNKNOWN = 'MCP API BLOCKED UNKNOWN COMMAND';
    case API_BLOCKED_GATE = 'MCP API BLOCKED BY GATE';
    case API_BLOCKED_COMMS = 'MCP API BLOCKED BY COMMS GATE';
    case API_CALL = 'MCP API CALL';
    case API_EXCEPTION = 'MCP API EXCEPTION';
    case API_OK = 'MCP API OK';
    case API_ERROR = 'MCP API ERROR';
    case API_MALFORMED = 'MCP API MALFORMED RESPONSE';
    case DB_BLOCKED = 'MCP DB WRITE BLOCKED';
    case DB_SELECT = 'MCP DB SELECT';
    case DB_INSERT = 'MCP DB INSERT';
    case DB_UPDATE = 'MCP DB UPDATE';
    case DB_DELETE = 'MCP DB DELETE';
    case DB_EXCEPTION = 'MCP DB EXCEPTION';
    case DB_OK = 'MCP DB OK';
    case PARTIAL_FINANCIAL = 'MCP PARTIAL FINANCIAL EFFECT';
    case CONFIRM_REQUIRED = 'MCP CONFIRMATION REQUIRED';
    case OAUTH_TOKEN_DENIED = 'MCP OAUTH TOKEN EXCHANGE DENIED';
    case OAUTH_TOKEN_ISSUED = 'MCP OAUTH TOKEN ISSUED';
    case OAUTH_AUTH_DENIED = 'MCP OAUTH AUTHORIZATION DENIED';
    case OAUTH_AUTH_APPROVED = 'MCP OAUTH AUTHORIZATION APPROVED';
    case OAUTH_ORPHAN_REVOKED = 'MCP OAUTH ORPHAN TOKEN REVOKED';
    case ADMIN_BEARER_REGENERATED = 'MCP ADMIN BEARER TOKEN REGENERATED';
    case ADMIN_OAUTH_TOKEN_REVOKED = 'MCP ADMIN OAUTH TOKEN REVOKED';
    case ADMIN_OAUTH_EXPIRED_CLEANED = 'MCP ADMIN EXPIRED OAUTH TOKENS CLEANED';
    case ADMIN_OAUTH_ALL_REVOKED = 'MCP ADMIN ALL OAUTH TOKENS REVOKED';
    case ADMIN_OAUTH_CLIENT_REMOVED = 'MCP ADMIN OAUTH CLIENT REMOVED';
    case ADDON_MIGRATION_FAILED = 'MCP ADDON MIGRATION FAILED';
    case ADDON_MIGRATION_OK = 'MCP ADDON MIGRATION OK';
}
